# Generated by Django 4.0.4 on 2023-06-24 01:49

from django.db import migrations


def create_superuser(apps, schema_editor):
    User = apps.get_model("auth", "User")
    User.objects.create_superuser(
        username="admin", email="admin@example.com", password="admin"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
